name: hrm.hrm_act_v1_classifier@HierarchicalReasoningModel_ACTV1_Classifier
loss:
  name: losses@ACTClassificationLossHead

halt_exploration_prob: 0.1
halt_max_steps: 16

H_cycles: 2
L_cycles: 2

H_layers: 4
L_layers: 4

hidden_size: 512
num_heads: 8
expansion: 4

puzzle_emb_ndim: 0

pos_encodings: rope

num_classes: 10
